particle:
  # The height of the particles above the ground (in blocks)
  height: 1.0
  # The distance between the particles (in blocks)
  distance: 0.5
  # Particle visibility range (in blocks)
  range: 20
  # The distance from the border of the region for displaying particles (in blocks)
  boundary-threshold: 1.0
  # Particle update interval (in ticks, 20 ticks = 1 second)
  update-interval: 10
  # RGB color for safe particles (0-255)
  safe-color:
    red: 0
    green: 255
    blue: 0
  # RGB color for PvP particles (0-255)
  pvp-color:
    red: 255
    green: 0
    blue: 0