name: ParticleRegionDisplay
version: '${project.version}'
main: su.lxt3z.particleregiondisplay.Main
api-version: '1.20'
authors: [lxt3z]
depend: [ WorldGuard, FastAsyncWorldEdit ]
commands:
  toggleparticles:
    usage: /<command>